//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspoint.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietPlan
    {
        public int DietId { get; set; }
        public int Slots { get; set; }
        public string FoodType { get; set; }
        public int FatRatio { get; set; }
        public int CarbsRatio { get; set; }
        public int ProteinRatio { get; set; }
        public int TotalCalorie { get; set; }
        public int UserId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
