//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspoint.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseDetail
    {
        public int ExerciseID { get; set; }
        public string ExerciseType { get; set; }
        public string ExerciseFor { get; set; }
        public int TotalSet { get; set; }
        public string Rest { get; set; }
        public string Focus { get; set; }
        public string Equipement { get; set; }
        public string Time { get; set; }
        public string ExerciseName { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
