//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspoint.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int TransactionId { get; set; }
        public Nullable<int> Payment1 { get; set; }
        public int Discount { get; set; }
        public int UserId { get; set; }
        public int PlanId { get; set; }
        public long NationalId { get; set; }
    }
}
