//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspoint.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_cred
    {
        public int DebitCardNo { get; set; }
        public int CreditCardNo { get; set; }
        public int Expiry_Month { get; set; }
        public int Expiry_Year { get; set; }
        public int cvv { get; set; }
        public long Nid { get; set; }
        public int AtmPin { get; set; }
    
        public virtual Payment_cred Payment_cred1 { get; set; }
        public virtual Payment_cred Payment_cred2 { get; set; }
    }
}
