//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspoint.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTbl
    {
        public int Order_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Plan_id { get; set; }
        public string Plan_name { get; set; }
        public int Amount { get; set; }
    
        public virtual NutritionPlan NutritionPlan { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
